name: Build & Push Secure Image

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-secure-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: DockerHub Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} ./backend

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_IMAGE_NAME }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'os,library'
        continue-on-error: false

      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_IMAGE_NAME }}
